### ISSUE TITLE
Fails silently when custom settings doesn't exist

### ISSUE THREAD

**Issue by randompants** [jalama/drupdates#86]
```Traceback (most recent call last):
  File "/usr/local/bin/drupdates", line 8, in <module>
    load_entry_point('Drupdates==1.1.4', 'console_scripts', 'drupdates')()
  File "/Library/Python/2.7/site-packages/Drupdates-1.1.4-py2.7.egg/drupdates/updates.py", line 12, in main
    sites = repos().get()
  File "/Library/Python/2.7/site-packages/Drupdates-1.1.4-py2.7.egg/drupdates/constructors/repos.py", line 11, in __init__
    self._plugin = self._tool
  File "/Library/Python/2.7/site-packages/Drupdates-1.1.4-py2.7.egg/drupdates/constructors/repos.py", line 27, in _plugin
    self.__plugin = self.loadPlugin(plugins[value])
KeyError: ''```

**Comment by jalama** [comment]
This looks to be due to an issue with the set-up, ie a missing $HOME/.drupdate/setting,yaml file.  Drupdates should still warn the user that the file is missing in Settings().  Rename this and added to the 1.2 release
